# frozen_string_literal: true
source "https://rubygems.org"

gem "rake", "~> 13.0"
gem "rawfeed", "~> 0.3.2"

# Windows and JRuby
platforms :windows, :jruby do
  gem "tzinfo", "~> 1.2"
  gem "tzinfo-data"
end

# Windows file watcher
gem "wdm", "~> 0.1.1", platforms: [:windows]
