#!/usr/bin/env ruby
require "rawfeed/tools"

cmd  = ARGV.shift

case cmd
when "minify"
  Rawfeed::Tools.minify
when "clean"
  Rawfeed::Tools.clean(*ARGV)
when "help"
  Rawfeed::Tools.help
else
  puts "Usage: rawfeed-tools [minify|clean|help] [options]"
end
